[ERROR] 2019-10-30 17:00:21,737 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:01:21,862 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:01:21,867 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:02:21,980 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:02:21,985 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:03:22,128 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:03:22,133 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:04:22,326 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:04:22,329 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:05:22,515 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:05:22,520 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:06:22,735 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:06:22,741 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:07:22,939 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:07:22,941 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:08:23,131 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:08:23,137 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:09:23,353 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:09:23,358 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:10:23,575 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:10:23,580 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:11:23,767 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:11:23,773 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:12:24,001 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:12:24,006 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:13:24,188 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:13:24,194 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:14:24,382 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:14:24,387 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:15:24,574 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:15:24,579 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:16:24,767 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:16:24,773 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:17:24,950 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:17:24,955 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:18:25,148 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:18:25,153 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:19:25,351 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:19:25,354 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:20:25,548 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:20:25,553 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:21:25,734 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:21:25,737 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:22:25,927 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:22:25,933 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:23:26,135 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:23:26,141 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:24:26,342 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:24:26,344 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:25:26,556 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:25:26,561 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:26:26,779 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:26:26,784 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:27:26,971 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:27:26,975 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-10-30 17:28:27,174 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 82, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 229, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 238, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 552, in get_single_value
    `tabSingles` where `doctype`=%s and `field`=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

